### ISSUE TITLE
This may work better for most if...

### ISSUE THREAD

**Issue by mlocke317** [hicknhack-software/redmine_hourglass#156] opened 2022-09-12 18:02 UTC
Since Redmine is a collaboration tool, please consider tracking time by issue and or project. We charge based on how long an issue is open and would like to start a timer per project/issue; instead of a specific user's time entry. Alternatively, we'd like to have the ability to run a timer on multiple projects, instead of being required to stop ongoing timers to begin another.  I would consider paying for this to be developed as a contribution.

**Comment by arBmind** [comment] 2022-09-12 21:46
Hi @mlocke317, this seems to be a duplicate of #125. That is outside of the scope of this project.

**Closed as completed by arBmind** 2022-09-12 21:46 UTC
Labels: duplicate

**Comment by mlocke317** [comment] 2022-09-13 02:03
It is the same, which is why I offered to help pay as contribution. On Sep 12, 2022, at 4:46 PM, Andreas Reischuck ***@***.***> wrote:﻿
Hi @mlocke317, this seems to be a duplicate of #125. That is outside of the scope of this project.
