### ISSUE TITLE
Not evidencing the time logged via regular Redmine "Log time" option

### ISSUE THREAD

**Issue by ctchtc** [hicknhack-software/redmine_hourglass#53] opened 2017-10-03 08:01 UTC
Dear Sirs,
When someone log time via the Redmine regular option "Log time" available on issues menu, this time is not evidenced in the reports generated by Hourglass Plugin, this making the reports innacurate.

**Comment by arBmind** [comment] 2017-10-03 13:52
This seems to be a duplicate of #14

**Closed by arBmind** 2017-10-03 13:52 UTC

**Comment by jume-dev** [comment] 2017-10-04 07:54
@arBmind is correct, this is a feature not yet implemented yet, consider giving a +1 in that other issue to show you need that feature :)
